name: Deploy Spring Boot Application to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 17

      # - name: Build with Gradle
      #   run: ./gradlew build

      # - name: Build Docker Image
      #   run: docker build . -t your-image-name:latest

      # - name: Save Docker image
      #   run: docker save your-image-name:latest > image.tar

      - name: Decode SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 -d -i > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Execute Remote Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: $HOME/.ssh/id_rsa
          script: |
            mkdir hello

      # - name: Copy Docker Image to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: $HOME/.ssh/id_rsa
      #     source: "image.tar"
      #     target: "/tmp"

      # - name: Deploy Docker Container on EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: $HOME/.ssh/id_rsa
      #     script: |
      #       docker load < /tmp/image.tar
      #       docker stop my-spring-app || true
      #       docker rm my-spring-app || true
      #       docker run --name my-spring-app -d -p 80:8080 your-image-name:latest
