name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export MY_NAME=${{ secrets.GH_USERNAME }}
            export MY_TOKEN=${{ secrets.GH_PAT }}
            git config --global user.name "$MY_NAME"
            echo "url=https://$MY_NAME:$MY_TOKEN@github.com" > ~/.git-credentials
            cd keemjipang/StoragePang
            pwd
            ls -al
            git config --global credential.helper store
            git pull origin
            mkdir test
            pwd
            ls -al

            
