name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
            export PATH=$JAVA_HOME/bin:$PATH
            echo "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
            git config --global credential.helper store
            cd keemjipang/StoragePang
            git pull origin
            ./gradlew build
            cd ..
            TAG=$(date +%Y%m%d%H%M%S)
            docker build --build-arg JAR_FILE=build/libs/demo-0.0.1-SNAPSHOT.jar --build-arg KEYSTORE_FILE=keystore.p12 -t demo-image:$TAG .
            echo "Docker image build status: $?"
            echo "Listing Docker Images..."
            docker images
