name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/keemjipang/Storagepang
            pwd
            ls -al
            git config --global credential.helper store
            echo url=https://Kimjipang:${{ secrets.GH_PAT }}@github.com > ~/.git-credentials
            git pull origin
            ./gradlew build
            mkdir test
            pwd
            ls -al


            
